#title
print("        ,----,                                                                                                                                          ")
print("      ,/   .`|                                                                                                                                          ")
print("    ,`   .'  :  ,---,                         ,---,                                                   ,--,                                              ")
print("  ;    ;     /,--.' |                        '  .' \      ,-.----.                                  ,--.'|             ,-.----.                         ")
print(".'___,/    ,' |  |  :                       /  ;    '.    \    /  \    ,---.                        |  | :             \    /  \                        ")
print("|    :     |  :  :  :                      :  :       \   |   :    |  '   ,'\                       :  : '             |   :    |  .--.--.              ")
print(";    |.';  ;  :  |  |,--.   ,---.          :  |   /\   \  |   | .\ : /   /   |   ,---.     ,--.--.  |  ' |        .--, |   | .\ : /  /    '     ,---.   ")
print("`----'  |  |  |  :  '   |  /     \         |  :  ' ;.   : .   : |: |.   ; ,. :  /     \   /       \ '  | |      /_ ./| .   : |: ||  :  /`./    /     \  ")
print("    '   :  ;  |  |   /' : /    /  |        |  |  ;/  \   \|   |  \ :'   | |: : /    / '  .--.  .-. ||  | :   , ' , ' : |   |  \ :|  :  ;_     /    /  | ")
print("    |   |  '  '  :  | | |.    ' / |        '  :  | \  \ ,'|   : .  |'   | .; :.    ' /    \__\/: . .'  : |__/___/ \: | |   : .  | \  \    `. .    ' / | ")
print("    '   :  |  |  |  ' | :'   ;   /|        |  |  '  '--'  :     |`-'|   :    |'   ; :__   ,\" .--.; ||  | '.'|.  \  ' | :     |`-'  `----.   \'   ;   /|")
print("    ;   |.'   |  :  :_:,''   |  / |        |  :  :        :   : :    \   \  / '   | '.'| /  /  ,.  |;  :    ; \  ;   : :   : :    /  /`--'  /'   |  / | ")
print("    '---'     |  | ,'    |   :    |        |  | ,'        |   | :     `----'  |   :    :;  :   .'   \  ,   /   \  \  ; |   | :   '--'.     / |   :    | ")
print("              `--''       \   \  /         `--''          `---'.|              \   \  / |  ,     .-./---`-'     :  \  \`---'.|     `--'---'   \   \  / ")
print("                           `----'                           `---`               `----'   `--`---'                \  ' ;  `---`                 `----'   ")
print("                                                                                                                  `--`                                  ")
print("\n")



#death message
def death():
    print("                                 _____  _____                           ")
    print("                                <     `/     |                          ")
    print("                                 >          (                           ")
    print("                                |   _     _  |                          ")
    print("                                |  |_) | |_) |                          ")
    print("                                |  | \ | |   |                          ")
    print("                                |            |                          ")
    print("                 ______.______%_|            |__________  _____         ")
    print("               _/                                       \|     |        ")
    print("              |               D U M B   A S S                  <        ")
    print("              |_____.-._________              ____/|___________|        ")
    print("                                | * 10/9/30  |                          ")
    print("                                |            |                          ")
    print("                                |            |                          ")
    print("                                |            |                          ")
    print("                                |   _        <                          ")
    print("                                |__/         |                          ")
    print("                                 / `--.      |                          ")
    print("                               %|            |%                         ")
    print("                           |/.%%|          -< @%%%                      ")
    print("                           `\%`@|     v      |@@%@%%                    ")
    print("                         .%%%@@@|%    |    % @@@%%@%%%%                 ")
    print("                    _.%%%%%%@@@@@@%%_/%\_%@@%%@@@@@@@%%%%%%             ")

#room3
def followman():
    print("the man says that he knows a base three miles south of here")
    print("do you either")
    print("a)follow him")
    print("b)spend the night alone")
    c =input("enter a or b")
    if c == "a":
        print("")
    elif c == "b":
        print("")
    
    

#room2


def man():
    print("you run towards the  warehouse and slam the door behind yourself The man jolts around and aims a crossbow at our head")
    print("            .-.        ")
    print("           /  \\       ")                      
    print("      .---/-+--||      ")                      
    print("     |  K=====++->     ")                       
    print("      '---\-+--||      ")                         
    print("           \  //       ")                         
    print("            `-'        ")
    print("Do you Either")
    print("a) talk to him")
    print("b) Go and try and kill the man")
    b = input("Enter a or b: ")
    if b == "a":
        print("you call out to him explaining you cause no harm")
        if name == ross:
            print("your lack of any social skills concludes with you ")
            print("messing up  and being shot")
            print("                                                       |")
        print("                                                        \.")
        print("                                                        /|.")
        print("                                                      /  `|.")
        print("                                                    /     |.")
        print("                                                  /       |.")
        print("                                                /         `|.")
        print("                                              /            |.")
        print("                                            /              |.")
        print("                                          /                |.")
        print("     __                                 /                  `|.")
        print("      -\                              /                     |.")
        print("        \\                          /                       |.")
        print("          \\                      /                         |.")
        print("           \|                   /                           ||")
        print("             \#####\          /                             ||")
        print("         ==###########>     /                               ||")
        print("          \##==      \    /                                 ||")
        print("     ______ =       =|__/___                                ||")
        print(" ,--' ,----`-,__ ___/'  --,-`-==============================##==========>")
        print("\               '        ##_______ ______   ______,--,____,=##,__")
        print(" `,    __==    ___,-,__,--'#'  ==='      `-'              | ##,-/")
        print("   `-,____,---'       \####\              |        ____,--\_##,/")
        print("       #_              |##   \  _____,---==,__,---'         ##")
        print("        #              ]===--==\                            ||")
        print("        #,             ]         \                          ||")
        print("         #_            |           \                        ||")
        print("         ##_       __/'             \                      ||")
        print("           ####='     |                \                    |/")
        print("            ###       |                  \                  |.")
        print("            ##       _'                    \                |.")
        print("           ###=======]                       \              |.")
        print("          ///        |                         \           ,|.")
        print("          //         |                           \         |.")
        print("                                                   \      ,|.")
        print("                                                     \    |.")
        print("                                                       \  |.")
        print("                                                         \|.")
        print("                                                         /.")
        print("                                                        |")
        death()
        quit()
    
    elif b == "b":
        print("The last thing you ever fell is cold metal slide through your head")
        print("\n")
        death()
    else:
        print("That was not an option.  Game Over")



#introduction
print("The year was 2036 a new Pathogen was released by a terrorist organization wanting to create a new world  ")
print("order it was spread from across the world before anyone noticed.The virus had a rabies gene that lead humans")
print("2 months later the world is in collapse business, governments and civilization fell into collapse the people")
print("Who are still alive search in the shadows for what is left trying to rebuild there reality.")
print("\n")
print("\n")
print("choose your character")
print("a)Harry")
print("abilities) neckback")
print("disability)low 1Q ,no parents")
print("    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print(" XXXXXXXXXXXXXXXXXX         XXXXXXXX")
print("XXXXXXXXXXXXXXXX              XXXXXXX")
print("XXXXXXXXXXXXX                   XXXXX")
print(" XXX     _________ _________     XXX")     
print("  XX    I  _xxxxx I xxxxx_  I    XX")        
print(" ( X----I         I         I----X )")          
print("( +I    I      00 I 00      I    I+ )")
print(" ( I    I    __0  I  0__    I    I )")
print("  (I    I______ /   \_______I    I)")
print("   I           ( ___ )           I")
print("   I    _  :::::::::::::::  _    i")
print("    \    \___ ::::::::: ___/    /")
print("     \_      \_________/      _/")
print("       \        \___,        /")
print("         \                 /")
print("          |\             /|")
print("          |  \_________/  |")
print("b) Ross ")
print("abilities) High IQ")
print("disability) socially awkward")
print("                        ;;\\/;;;;;;;;")
print("                   ;;;;;;;;;;;;;;;;;")
print("                ;;;;;;;;;;;;     ;;;;;")
print("               ;;;;;    ;;;         \;;")
print("              ;;;;;      ;;          |;")
print("             ;;;;         ;          |")
print("            ;;;                     |")
print("             ;;                     )")
print("               \    ~~~~ ~~~~~~~    /")
print("                \    ~~~~~~~  ~~   /")
print("              |\ \                / /|")
print("               \\| %%%%%    %%%%% |//")
print("              [[====================]]")
print("               | |  ^          ^  |")
print("              | | :@: |/  \| :@: | |")
print("                \______/\  /\______/")
print("                 |     (@\/@)     |")
print("                /                  |")
print("               /  ;-----\  ______;  |")
print("               \         \/         /")
print("                )                  (")
print("               /                    |")
print("               \__                  /")
print("                \_                _/")
print("                 \______/\/\______/")
print("                  |               | ")
print("c) henry")
print("abilities) Strong , stamina ")
print("disabilities) cake")
print("                 ,#####,")
print("                 #_   _#")
print("                 |a` `a|")
print("                 |  u  |")
print("                 \  =  /")
print("                 |\___/|")
print("        ___ ____/:     :\____ ___")
print("      .'   `.-===-\   /-===-.`   '.")
print("     /      .-....._.-....-.      |")
print("    /'             =:=             '|")
print("  .'  ' .:    o   -=:=-   o    :. '  `.")
print("  (.'   /'. '-.....-'-.....-' .'\   '.)")
print("  /' ._/   ..     --:--     ..   \_. '|")
print(" |  .'|      ..  ---:---  .      |'.  |")
print(" |  : |       |  ---:---  |       | :  |")
print("  \ : |       |_____._____|       | : /")
print("  /   (       |----|------|       )   |")
print(" /... .|      |    |      |      |. ...|")
print("|::::/''     /     |       \     ''\::::|")
print("'....       /'    .L_      `\       ....'")
print("           /'-.,__/` `\__..-'|")
print("          ;      /     \      ;")
print("          :     /       \     |")
print("          |    /         \.   |")
print("          |`../           |  ,/")
print("         ( _ )           |  _)")
print("          |   |           |   |")
print("          |___|           \___|")
print("          :===|            |==|")
print("           \  /            |__|")
print("           /\/\           /....--")
print("           |oo|           \__.//___)")
print("           |==|")
print("           \__/")
name = input("choose your charecter")
harry = "a"
ross = "b"
henry = "c"
if name == harry:
    print("your retard self gets wheelchair stuck in the ")
    print("gutter you dont last long before the zombie's get to you ")
    print("you start bluffing relising how crippled you are and that your only")
    print("achievement was knowing henry in secondary school")
    print("your life flashes before your eyes you see ")
    print("the day his mum was so ugly his dad had a husband")
    print("your brains lied on the floor ")
    print("      .__---~~~~~-_.")
    print("   _-'  \) -~~- \) _-- ")
    print("  (  ( `-,_..`.,_--_ '_,\)_")
    print(" (  -_\)  ( -_-~  -_ `,    )")
    print(" (_ -_ _-~-__-~`, ,' )__-'))--___--~~~--__--~~--___--__..")
    print(" _ ~`_-'( (____;--==,,_))))--___--~~~--__--~~--__----~~~'`=__-~+_-_.")
    print("(@) (@) `````      `-_(())_-~  ")
    death()
    quit()

    
#room 1
print("You Sprint down the street running from the zombies,you hear voices coming from inside a abondened warehouse.")
print("Do you Either")
print("a) keep on running.")
print("b) Go  and investigate")
x = input("Enter a or b: ")
if x == "a":
    print("The zombies hunt you down and trap you against the wall You died")
    death()
elif x == "b":
    print("You go in to investigate.")
    print("A man dressed in tattered old clothing turns around aims his crossbow at your head")
    man()
else:
    print("That was not an option.  Game Over")
    print("question your life choises")
    death()
